name: MSBuild

on:
  push:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: DataOrientedBoids.sln

  BUILD_CONFIGURATION: Release

permissions:
  contents: write
 
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Set PowerShell Execution Policy
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        Write-Host "ExecutionPolicy is now:" (Get-ExecutionPolicy)

    - name: Install NuGet
      run: |
        Invoke-WebRequest https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe

    - name: NuGet restore
      run: ./nuget.exe restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Copy OpenCV DLL into build folder
      shell: powershell
      run: |
        Copy-Item C:\opencv\build\x64\vc16\bin\opencv_world4120.dll x64\Release\

    - name: Zip build folder
      shell: powershell
      run: |
        Compress-Archive -Path x64\Release\* -DestinationPath x64\Release\BuildResult.zip -Force

    - uses: actions/upload-artifact@v4
      with:
        name: BuildResult.zip
        path: x64\Release\BuildResult.zip

  upload:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4.3.0
      with:
        name: BuildResult.zip
        path: x64\Release\

    - name: Create tag
      id: tag
      run: |
        $tag = (Get-Date -Format "yyyy.MM.dd.HH;mm")
        git tag $tag
        git push origin $tag
        echo "TAG=$tag" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG }}
        release_name: Release ${{ env.TAG }}
        body: "Release created automatically"
        draft: false
        prerelease: false

    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: x64\Release\BuildResult.zip
        asset_name: DataOrientedBoids.zip
        asset_content_type: application/zip
